// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Query struct {
}

type Questions struct {
	Notes   string `json:"notes"`
	Correct *bool  `json:"correct,omitempty"`
}

type QuestionsInput struct {
	Notes   string `json:"notes"`
	Correct *bool  `json:"correct,omitempty"`
}

type SavedQuiz struct {
	UserID    string       `json:"userId"`
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	Responses []*Questions `json:"responses,omitempty"`
}

type SavedQuizInput struct {
	UserID    string            `json:"userId"`
	ID        string            `json:"id"`
	Name      string            `json:"name"`
	Responses []*QuestionsInput `json:"responses,omitempty"`
}

type User struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UserInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}
